const fs = require('fs');
const path = require('path');

function walk(dir) {
  let results = [];
  const list = fs.readdirSync(dir);
  list.forEach(function(file) {
    file = path.join(dir, file);
    const stat = fs.statSync(file);
    if (stat && stat.isDirectory()) { 
      results = results.concat(walk(file));
    } else if (file.endsWith('.ts')) { 
      results.push(file);
    }
  });
  return results;
}

const files = walk('src');
let changed = 0;
files.forEach(file => {
  const content = fs.readFileSync(file, 'utf8');
  if (content.includes('( as Error)')) {
    // We need to restore the correct variable name.
    // Let's look at the catch clause or surrounding context to find the error variable.
    // A simple regex might not work, but we can look for "catch (errVar)" before it.
    let newContent = content.replace(/catch\s*\(\s*(\w+)\s*([^)]*)\)\s*\{([\s\S]*?)\}/g, (match, errVar, rest, body) => {
        return 'catch (' + errVar + rest + ') {' + body.replace(/\( as Error\)/g, '(' + errVar + ' as Error)') + '}';
    });
    
    // Fallback for cases outside catch blocks (e.g. verifyError in a loop)
    // Actually, all of these were generated by my previous script where I matched TS errors:
    // TS18046: 'primaryError' is of type 'unknown'.
    newContent = newContent.replace(/\( as Error\)/g, '(error as Error)'); // fallback
    
    if (content !== newContent) {
      fs.writeFileSync(file, newContent, 'utf8');
      changed++;
    }
  }
});
console.log('Fixed ( as Error) in ' + changed + ' files.');
