// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { resolve } from 'path';
import { config as loadEnv } from 'dotenv';
import { defineConfig } from 'prisma/config';

// Canonical file is repo-root .env. backend-nest/.env fills any missing keys.
loadEnv({ path: resolve(__dirname, '../.env') });
loadEnv({ path: resolve(__dirname, '.env') });

// Supabase (and many managed Postgres providers) require SSL and will reject
// plain connections. Railway environments often supply `DATABASE_URL` but
// omit the `sslmode=require` query parameter, which leads to a P1001 error
// when Prisma/pg tries to connect:
//
//   Error: P1001: Can't reach database server at `…supabase.co:5432`
//
// To guard against that, append the parameter automatically if it isn't
// already present. This keeps your deployment working even if the var is
// defined without SSL info.

function withPgSslCompat(url: string): string {
  if (!url || url.includes('localhost') || url.includes('127.0.0.1')) {
    return url;
  }
  const extra: string[] = [];
  const hasSslMode = /sslmode=/i.test(url);
  if (process.env.NODE_ENV === 'production' && !hasSslMode) {
    extra.push('sslmode=require');
  }
  const sslMode = (
    url.match(/sslmode=([^&]+)/i)?.[1] ||
    (extra.includes('sslmode=require') ? 'require' : '')
  ).toLowerCase();
  if (
    ['require', 'prefer', 'verify-ca'].includes(sslMode) &&
    !/uselibpqcompat=/i.test(url)
  ) {
    extra.push('uselibpqcompat=true');
  }
  if (extra.length === 0) return url;
  return `${url}${url.includes('?') ? '&' : '?'}${extra.join('&')}`;
}

if (process.env.DATABASE_URL) {
  process.env.DATABASE_URL = withPgSslCompat(process.env.DATABASE_URL);
}

if (process.env.DIRECT_DATABASE_URL) {
  process.env.DIRECT_DATABASE_URL = withPgSslCompat(
    process.env.DIRECT_DATABASE_URL,
  );
}

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // For Prisma 7, 'url' in the config is used by Migrate/Introspection commands.
    // To avoid hanging on Supabase poolers, we use the direct connection (5432) here.
    url:
      process.env.DIRECT_DATABASE_URL ||
      process.env.DATABASE_URL ||
      'postgresql://postgres:postgres@localhost:5432/postgres?schema=public',
  },
});
