import Link from 'next/link';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';

export default function TermsPage() {
    return (
        <div className="container mx-auto px-4 py-12 max-w-4xl">
            <div className="mb-8 text-center">
                <h1 className="text-4xl font-bold tracking-tight">Terms of Service</h1>
                <p className="mt-4 text-muted-foreground">
                    Last updated: {new Date().toLocaleDateString()}
                </p>
            </div>

            <div className="space-y-6">
                <Card>
                    <CardHeader>
                        <CardTitle>1. Introduction</CardTitle>
                        <CardDescription>
                            Please read these terms carefully before using our presentation design services.
                        </CardDescription>
                    </CardHeader>
                    <CardContent>
                        <p className="leading-7">
                            By using our application ("PresentationDesigner"), you agree to be bound by these Terms of Service.
                            If you do not agree to these terms, please do not use our services.
                        </p>
                    </CardContent>
                </Card>

                <Card>
                    <CardHeader>
                        <CardTitle>2. Content & Copyright</CardTitle>
                    </CardHeader>
                    <CardContent className="space-y-4">
                        <h3 className="font-semibold">User Responsibility</h3>
                        <p>
                            You are solely responsible for the content you generate, import, or upload using our tools.
                            By importing content from URLs ("URL Import"), you confirm that you have the right to access and use the content from those URLs.
                        </p>

                        <h3 className="font-semibold">AI Generated Content</h3>
                        <p>
                            Content generated by AI is provided "as-is". While we strive for accuracy, AI models may produce hallucinations or inaccuracies.
                            You should verify all generated content before presenting or publishing it.
                            Subject to applicable laws and third-party AI provider terms (OpenAI, Google), you generally own the rights to the content you generate.
                        </p>

                        <h3 className="font-semibold">Prohibited Content</h3>
                        <p>
                            You may not use our service to generate:
                        </p>
                        <ul className="list-disc pl-5">
                            <li>Hate speech or harassment</li>
                            <li>Sexually explicit content</li>
                            <li>Content that violates third-party intellectual property rights</li>
                            <li>Misinformation or deceptive content</li>
                        </ul>
                    </CardContent>
                </Card>

                <Card>
                    <CardHeader>
                        <CardTitle>3. Third-Party Services</CardTitle>
                    </CardHeader>
                    <CardContent>
                        <p>
                            Our application integrates with third-party services like Unsplash, Pexels, Google, and OpenAI.
                            Your use of these features is also subject to their respective Terms of Service and Privacy Policies.
                        </p>
                    </CardContent>
                </Card>

                <Card>
                    <CardHeader>
                        <CardTitle>4. Limitation of Liability</CardTitle>
                    </CardHeader>
                    <CardContent>
                        <p>
                            PresentationDesigner is provided on an "AS IS" and "AS AVAILABLE" basis. We disclaim all liability for any
                            damages arising from your use of the service, including but not limited to direct, indirect, incidental,
                            punitive, and consequential damages.
                        </p>
                    </CardContent>
                </Card>
            </div>

            <div className="mt-12 text-center text-sm text-muted-foreground">
                <p>
                    Need help? <Link href="/contact" className="underline hover:text-primary">Contact Support</Link>
                </p>
            </div>
        </div>
    );
}
