'use client';

import { useState } from 'react';
import { useMutation } from '@tanstack/react-query';
import {
    RefreshCw,
    Wand2,
    Trash2,
    Loader2,
    Sparkles,
    Download,
    Image as ImageIcon,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
    Tooltip,
    TooltipContent,
    TooltipProvider,
    TooltipTrigger,
} from '@/components/ui/tooltip';
import { cn } from '@/lib/utils';

interface ImageAIControlsProps {
    imageUrl?: string;
    imageAlt?: string;
    blockId: string;
    slideId: string;
    projectId: string;
    onImageUpdate?: (newUrl: string, newAlt?: string) => void;
    onDelete?: () => void;
}

export function ImageAIControls({
    imageUrl,
    imageAlt,
    blockId,
    slideId,
    projectId,
    onImageUpdate,
    onDelete,
}: ImageAIControlsProps) {
    const [isHovered, setIsHovered] = useState(false);
    const [isRegenerating, setIsRegenerating] = useState(false);

    const regenerateImageMutation = useMutation({
        mutationFn: async () => {
            const response = await fetch('/api/ai/regenerate-image', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    projectId,
                    slideId,
                    blockId,
                    currentImage: imageUrl,
                    prompt: imageAlt || 'Generate a relevant presentation image',
                }),
            });
            return response.json();
        },
        onSuccess: (data: { imageUrl?: string; alt?: string }) => {
            if (data?.imageUrl) {
                onImageUpdate?.(data.imageUrl, data.alt);
            }
        },
    });

    const enhanceImageMutation = useMutation({
        mutationFn: async () => {
            const response = await fetch('/api/ai/enhance-image', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    projectId,
                    imageUrl,
                }),
            });
            return response.json();
        },
        onSuccess: (data: { imageUrl?: string }) => {
            if (data?.imageUrl) {
                onImageUpdate?.(data.imageUrl);
            }
        },
    });

    const handleRegenerate = () => {
        setIsRegenerating(true);
        regenerateImageMutation.mutate();
        setTimeout(() => setIsRegenerating(false), 2000);
    };

    return (
        <div
            className="relative group/image w-full h-full"
            onMouseEnter={() => setIsHovered(true)}
            onMouseLeave={() => setIsHovered(false)}
        >
            {/* Image */}
            {imageUrl ? (
                <div className="w-full h-full rounded-xl overflow-hidden bg-slate-50 dark:bg-slate-800 relative">
                    <img
                        src={imageUrl}
                        alt={imageAlt || "Image"}
                        className="object-cover w-full h-full"
                    />

                    {/* Gradient overlay */}
                    <div className="absolute inset-0 bg-gradient-to-t from-slate-900/40 to-transparent opacity-0 group-hover/image:opacity-100 transition-opacity" />

                    {/* AI Generated badge */}
                    <div className="absolute bottom-4 left-4 text-white font-medium text-sm bg-black/30 backdrop-blur-md px-3 py-1 rounded-full border border-white/20">
                        <Sparkles className="inline h-3 w-3 mr-1" />
                        Generated by AI
                    </div>

                    {/* Top Right AI Controls */}
                    <div className={cn(
                        "absolute top-4 right-4 flex gap-2 transition-all duration-200",
                        isHovered ? "opacity-100 translate-y-0" : "opacity-0 -translate-y-2"
                    )}>
                        <TooltipProvider>
                            <Tooltip>
                                <TooltipTrigger asChild>
                                    <button
                                        onClick={handleRegenerate}
                                        disabled={regenerateImageMutation.isPending}
                                        className="bg-white/90 backdrop-blur text-slate-700 hover:text-blue-600 px-3 py-1.5 rounded-md text-xs font-semibold shadow-sm flex items-center gap-1 transition-colors"
                                    >
                                        {regenerateImageMutation.isPending ? (
                                            <Loader2 className="h-3.5 w-3.5 animate-spin" />
                                        ) : (
                                            <RefreshCw className="h-3.5 w-3.5" />
                                        )}
                                        Regenerate
                                    </button>
                                </TooltipTrigger>
                                <TooltipContent>Generate a new AI image</TooltipContent>
                            </Tooltip>

                            <Tooltip>
                                <TooltipTrigger asChild>
                                    <button
                                        onClick={() => enhanceImageMutation.mutate()}
                                        disabled={enhanceImageMutation.isPending}
                                        className="bg-white/90 backdrop-blur text-slate-700 hover:text-purple-600 p-1.5 rounded-md shadow-sm transition-colors"
                                    >
                                        {enhanceImageMutation.isPending ? (
                                            <Loader2 className="h-3.5 w-3.5 animate-spin" />
                                        ) : (
                                            <Wand2 className="h-3.5 w-3.5" />
                                        )}
                                    </button>
                                </TooltipTrigger>
                                <TooltipContent>Enhance image quality</TooltipContent>
                            </Tooltip>

                            <Tooltip>
                                <TooltipTrigger asChild>
                                    <button
                                        onClick={onDelete}
                                        className="bg-white/90 backdrop-blur text-slate-700 hover:text-red-600 p-1.5 rounded-md shadow-sm transition-colors"
                                    >
                                        <Trash2 className="h-3.5 w-3.5" />
                                    </button>
                                </TooltipTrigger>
                                <TooltipContent>Remove image</TooltipContent>
                            </Tooltip>
                        </TooltipProvider>
                    </div>
                </div>
            ) : (
                <div className="w-full aspect-video bg-slate-200 dark:bg-slate-700 rounded-xl flex flex-col items-center justify-center gap-3 border-2 border-dashed border-slate-300 dark:border-slate-600">
                    <ImageIcon className="h-8 w-8 text-slate-400" />
                    <div className="flex gap-2">
                        <Button
                            variant="outline"
                            size="sm"
                            onClick={handleRegenerate}
                            disabled={regenerateImageMutation.isPending}
                        >
                            {regenerateImageMutation.isPending ? (
                                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                            ) : (
                                <Sparkles className="h-4 w-4 mr-2" />
                            )}
                            AI Generate
                        </Button>
                        <Button variant="outline" size="sm">
                            <Download className="h-4 w-4 mr-2" />
                            Upload
                        </Button>
                    </div>
                </div>
            )}
        </div>
    );
}
